// <auto-generated />
namespace OnlineShopWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updateorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateorder));
        
        string IMigrationMetadata.Id
        {
            get { return "202412151509317_updateorder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
